[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
bs4 = "*"
flask = "*"
pafy = "*"
python = "^3.8"
requests = "*"
youtube-dl = "*"
